language: java

jdk:
  - oraclejdk8

install: ./gradlew clean assemble --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "TODO"
    - secure: "TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
